import java.io.*;
import java.util.*;

/**
 * This class reads the input files generated by GenerateInfoFiles
 * and generates the required reports:
 * 1. Total money per salesman (sorted descending)
 * 2. Total quantity sold per product (sorted descending)
 */
public class main {

    public static void main(String[] args) {

        try {
            // Load salesmen and products
            Map<Long, String> salesmen = loadSalesmen();
            Map<Integer, Product> products = loadProducts();

            // Totals
            Map<Long, Integer> salesmanTotals = new HashMap<>();
            Map<Integer, Integer> productTotals = new HashMap<>();

            // Read sales files
            File folder = new File("data");
            File[] files = folder.listFiles();

            if (files != null) {
                for (File file : files) {

                    if (file.getName().startsWith("sales_") && file.getName().endsWith(".txt")) {

                        BufferedReader br = new BufferedReader(new FileReader(file));

                        // Header line
                        String line = br.readLine();
                        long id = Long.parseLong(line.split(";")[1]);

                        int totalMoney = 0;

                        // Process sales
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(";");
                            int productId = Integer.parseInt(parts[0]);
                            int quantity = Integer.parseInt(parts[1]);

                            int price = products.get(productId).price;
                            totalMoney += quantity * price;

                            productTotals.put(productId, productTotals.getOrDefault(productId, 0) + quantity);
                        }

                        salesmanTotals.put(id, totalMoney);
                        br.close();
                    }
                }
            }

            // Generate reports
            createSalesReport(salesmen, salesmanTotals);
            createProductReport(products, productTotals);

            System.out.println("Reports generated successfully ✅");

        } catch (Exception e) {
            System.out.println("Error generating reports ❌");
            e.printStackTrace();
        }
    }

    // Helper class to store product info
    static class Product {
        String name;
        int price;
        public Product(String name, int price) {
            this.name = name;
            this.price = price;
        }
    }

    // Load salesmen
    public static Map<Long, String> loadSalesmen() throws IOException {
        Map<Long, String> map = new HashMap<>();
        BufferedReader br = new BufferedReader(new FileReader("data/salesmen.txt"));
        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(";");
            long id = Long.parseLong(parts[1]);
            map.put(id, parts[2] + " " + parts[3]);
        }
        br.close();
        return map;
    }

    // Load products
    public static Map<Integer, Product> loadProducts() throws IOException {
        Map<Integer, Product> map = new HashMap<>();
        BufferedReader br = new BufferedReader(new FileReader("data/products.txt"));
        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(";");
            int id = Integer.parseInt(parts[0]);
            String name = parts[1];
            int price = Integer.parseInt(parts[2]);
            map.put(id, new Product(name, price));
        }
        br.close();
        return map;
    }

    // Generate sales report
    public static void createSalesReport(Map<Long, String> salesmen, Map<Long, Integer> totals) throws IOException {
        List<Map.Entry<Long, Integer>> list = new ArrayList<>(totals.entrySet());
        list.sort((a, b) -> b.getValue() - a.getValue());

        FileWriter writer = new FileWriter("data/sales_report.csv");
        for (Map.Entry<Long, Integer> entry : list) {
            long id = entry.getKey();
            writer.write(salesmen.get(id) + ";" + entry.getValue() + "\n");
        }
        writer.close();
    }

    // Generate product report
    public static void createProductReport(Map<Integer, Product> products, Map<Integer, Integer> totals) throws IOException {
        List<Map.Entry<Integer, Integer>> list = new ArrayList<>(totals.entrySet());
        list.sort((a, b) -> b.getValue() - a.getValue());

        FileWriter writer = new FileWriter("data/product_report.csv");
        for (Map.Entry<Integer, Integer> entry : list) {
            int id = entry.getKey();
            writer.write(products.get(id).name + ";" + entry.getValue() + "\n");
        }
        writer.close();
    }
}